create table if not exists public.progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  status text check (status in ('correct','partial','incorrect')),
  mark_scheme_revealed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, question_id)
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text,
  event_type text not null,
  status text,
  input_tokens integer,
  output_tokens integer,
  estimated_cost_usd numeric(12,6),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.progress enable row level security;
alter table public.events enable row level security;

create policy "students read own progress" on public.progress for select using (auth.uid() = user_id);
create policy "students insert own progress" on public.progress for insert with check (auth.uid() = user_id);
create policy "students update own progress" on public.progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "students insert own events" on public.events for insert with check (auth.uid() = user_id);

create index if not exists events_question_idx on public.events(question_id);
create index if not exists events_created_idx on public.events(created_at desc);
