"use client";

import { useEffect, useMemo, useState } from "react";
import { Search, SlidersHorizontal, FileSearch, ExternalLink, X, Columns3, Send, ChevronDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { recordUsage } from "@/lib/usage-analytics";

type RecordItem=any;
const blank={q:"",topic:"",source:"",category:"",year:"",paper:"",question:"",relevance:"direct,close"};
const viewUrl=(id:string)=>`https://drive.google.com/file/d/${encodeURIComponent(id)}/view`;
const previewUrl=(id:string)=>`https://drive.google.com/file/d/${encodeURIComponent(id)}/preview`;

function SourceBadge({item}:{item:RecordItem}) {
  const cls=item.kind==="er"?"border-amber-200 bg-amber-50 text-amber-900":item.kind==="ms"?"border-indigo-200 bg-indigo-50 text-indigo-900":"border-sky-200 bg-sky-50 text-sky-900";
  return <Badge variant="outline" className={cls}>{item.sourceType} · {item.category}</Badge>
}

function Detail({item}:{item:RecordItem}) {
  const source=item.links?.[0];
  return <div className="space-y-6 pb-10">
    <div><p className="text-sm font-semibold text-teal-800">{item.topic} › {item.concept}</p><div className="mt-2"><SourceBadge item={item}/></div><h3 className="mt-3 text-xl font-semibold">{item.citation}</h3></div>
    <section><h4 className="text-sm font-bold uppercase tracking-wider text-slate-500">Question context</h4><div className="mt-2 rounded-xl border bg-slate-50 p-4"><p>{item.question||"No question extract is stored for this record."}</p></div></section>
    {!!item.points?.length&&<section><h4 className="text-sm font-bold uppercase tracking-wider text-slate-500">Mark scheme · atomic points</h4><ol className="mt-2 space-y-2">{item.points.map((p:any)=><li key={p.id||p.no} className="border-l-4 border-indigo-400 bg-indigo-50 p-3"><strong>MP{p.no} · {p.markType||"mark"}{p.value||""}</strong><p className="mt-1">{p.text}</p>{p.alternatives?.length?<p className="mt-1 text-sm text-slate-600">Alternatives: {p.alternatives.join(" · ")}</p>:null}{p.reject?<p className="mt-1 text-sm text-rose-800">Reject: {p.reject}</p>:null}</li>)}</ol></section>}
    <section><h4 className="text-sm font-bold uppercase tracking-wider text-slate-500">Cambridge source text</h4><div className="mt-2 rounded-xl border border-sky-200 bg-sky-50/70 p-4 leading-7">{item.evidence}</div></section>
    <section><h4 className="text-sm font-bold uppercase tracking-wider text-violet-700">Evidence classification</h4><div className="mt-2 rounded-xl border border-violet-200 bg-violet-50 p-4"><p>{item.classification||item.category}</p><dl className="mt-3 grid grid-cols-[9rem_1fr] gap-2 text-sm"><dt className="font-semibold text-slate-500">9478 LO</dt><dd>{item.lo||"No verified item-level mapping"}</dd><dt className="font-semibold text-slate-500">Source syllabus</dt><dd>{item.sourceSyllabus}</dd><dt className="font-semibold text-slate-500">9478 alignment</dt><dd>{item.alignment}</dd><dt className="font-semibold text-slate-500">Relevance</dt><dd>{item.relevance==="direct"?"Direct evidence":item.relevance==="close"?"Closely related evidence":"Contextual evidence"}</dd></dl></div></section>
    <section className="rounded-xl border border-teal-200 bg-teal-50 p-4"><h4 className="font-semibold">Original-source verification</h4><p className="mt-1 text-sm">{source?"A verified Drive source is mapped to this record.":"No authorised source document is mapped, so no link is shown."}</p><Badge variant="outline" className="mt-3 border-teal-300 text-teal-800">{source?"Verified Drive source":item.sourceQuality}</Badge>{source&&<div className="mt-3 flex flex-wrap gap-2">{item.links.map((s:any)=><a key={s.id} href={viewUrl(s.id)} target="_blank" rel="noreferrer" onClick={()=>recordUsage("source_opened",{source_type:s.kind,topic:item.topic||"Unmapped"})} className="inline-flex items-center gap-1 rounded-md bg-white px-3 py-2 text-sm font-semibold text-teal-800 ring-1 ring-teal-300">Open {s.kind}{s.page?` · p. ${s.page}`:""}<ExternalLink className="h-3.5 w-3.5"/></a>)}</div>}</section>
    {source&&<section><div className="mb-2 flex items-center justify-between gap-3"><h4 className="font-semibold">{source.title}</h4><span className="text-sm text-slate-500">{source.page?`Relevant passage: p. ${source.page}`:""}</span></div><iframe title={source.title} src={previewUrl(source.id)} loading="lazy" className="h-[58vh] w-full rounded-xl border bg-slate-100"/></section>}
  </div>
}

export default function EvidenceExplorer({onSend}:{onSend:(ids:string[])=>void}) {
  const [filters,setFilters]=useState(blank),[data,setData]=useState<any>({items:[],total:0,counts:{},relevanceCounts:{},options:{topics:[],categories:[],years:[],papers:[]}}),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Set<string>>(new Set()),[detail,setDetail]=useState<RecordItem|null>(null),[compare,setCompare]=useState(false),[mobileFilters,setMobileFilters]=useState(false);
  const params=useMemo(()=>{const p=new URLSearchParams({...filters,page:String(page)});return p.toString()},[filters,page]);
  useEffect(()=>{let live=true;setLoading(true);fetch("/api/explorer?"+params).then(r=>r.json()).then(x=>{if(live)setData((old:any)=>page===1?x:{...x,items:[...old.items,...x.items]})}).finally(()=>live&&setLoading(false));return()=>{live=false}},[params,page]);
  const selectedItems=data.items.filter((x:RecordItem)=>selected.has(x.id));
  const update=(key:string,value:string)=>{setPage(1);setFilters(f=>({...f,[key]:value}));if(key==="topic"&&value)recordUsage("topic_selected",{topic:value});if(key==="source"&&value)recordUsage("source_filter_selected",{source:value})};
  const clear=()=>{setPage(1);setFilters(blank)};
  const toggle=(id:string)=>setSelected(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});
  const filterBody=<div className="space-y-4">
    <div><label className="text-sm font-semibold">9478 topic</label><select value={filters.topic} onChange={e=>update("topic",e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-2.5 text-sm"><option value="">All topics</option>{data.options.topics?.map((x:string)=><option key={x}>{x}</option>)}</select></div>
    <div><label className="text-sm font-semibold">Source type</label><select value={filters.source} onChange={e=>update("source",e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-2.5 text-sm"><option value="">All source types</option><option value="er">Examiner Report</option><option value="ms">Question + Mark Scheme</option><option value="syllabus">Syllabus</option></select></div>
    <div><label className="text-sm font-semibold">Evidence category</label><select value={filters.category} onChange={e=>update("category",e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-2.5 text-sm"><option value="">All available categories</option>{data.options.categories?.map((x:string)=><option key={x}>{x}</option>)}</select></div>
    <div className="grid grid-cols-2 gap-2"><div><label className="text-sm font-semibold">Year</label><select value={filters.year} onChange={e=>update("year",e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-2.5 text-sm"><option value="">All</option>{data.options.years?.map((x:string)=><option key={x}>{x}</option>)}</select></div><div><label className="text-sm font-semibold">Paper</label><select value={filters.paper} onChange={e=>update("paper",e.target.value)} className="mt-1 w-full rounded-lg border bg-white p-2.5 text-sm"><option value="">All</option>{data.options.papers?.map((x:string)=><option key={x}>{x}</option>)}</select></div></div>
    <div><label className="text-sm font-semibold">Question number</label><Input value={filters.question} onChange={e=>update("question",e.target.value)} placeholder="e.g. 5" className="mt-1"/></div>
    <fieldset><legend className="text-sm font-semibold">Relevance</legend>{[["direct","Direct"],["close","Closely related"],["contextual","Contextual"]].map(([v,l])=><label key={v} className="mt-2 flex items-center gap-2 text-sm"><Checkbox checked={filters.relevance.split(",").includes(v)} onCheckedChange={()=>{const a=filters.relevance.split(",").filter(Boolean),n=a.includes(v)?a.filter(x=>x!==v):[...a,v];update("relevance",n.join(","))}}/>{l}</label>)}</fieldset>
    <Button variant="outline" onClick={clear} className="w-full">Clear all filters</Button><p className="border-t pt-3 text-xs leading-5 text-slate-500">Only categories represented in the current corpus are offered. Historical mappings remain qualified.</p>
  </div>;
  return <section>
    <div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-teal-700">Source-backed research and verification</p><h2 className="mt-1 text-2xl font-semibold">Evidence Explorer</h2><p className="mt-1 text-slate-600">Browse, inspect, verify, compare and collect the evidence behind Tab 1.</p></div>
    <div className="grid items-start gap-5 lg:grid-cols-[260px_minmax(0,1fr)]">
      <aside className="sticky top-4 hidden rounded-2xl border bg-white p-4 lg:block"><h3 className="mb-4 font-semibold">Corpus navigation</h3>{filterBody}</aside>
      <div className="min-w-0">
        <div className="flex gap-2"><Button variant="outline" className="lg:hidden" onClick={()=>setMobileFilters(true)}><SlidersHorizontal className="mr-2 h-4 w-4"/>Filters</Button><div className="flex flex-1 items-center rounded-xl border bg-white px-3"><Search className="h-5 w-5 text-slate-400"/><Input value={filters.q} onChange={e=>update("q",e.target.value)} placeholder="Search within Cambridge evidence…" className="border-0 shadow-none focus-visible:ring-0"/></div></div>
        <div className="my-5 rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-teal-700">Current evidence footprint</p><h3 className="mt-1 text-xl font-semibold">{filters.topic||filters.q||"Cambridge assessment evidence"}</h3><p className="mt-1 text-slate-600"><strong>{data.total}</strong> relevant records · <strong>{data.relevanceCounts.direct||0}</strong> direct · <strong>{data.relevanceCounts.close||0}</strong> closely related</p><div className="mt-3 flex flex-wrap gap-2">{Object.entries(data.counts||{}).slice(0,5).map(([k,n]:any)=><Badge key={k} variant="outline">{n} {k}</Badge>)}</div></div>
        <div className="space-y-3">{!loading&&!data.items.length?<div className="rounded-2xl border bg-white p-8"><h3 className="text-lg font-semibold">Limited direct evidence found</h3><p className="mt-2 text-slate-600">No records match the current scope. Broaden the filters or include contextual evidence; the Hub will not manufacture a conclusion.</p></div>:data.items.map((item:RecordItem)=><article key={item.id} className={`rounded-2xl border-l-4 bg-white p-5 shadow-sm ${item.kind==="er"?"border-amber-500":item.kind==="ms"?"border-indigo-500":"border-sky-500"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-600">{item.topic} › {item.concept}</p><div className="mt-2"><SourceBadge item={item}/></div></div><label className="flex items-center gap-2 text-sm"><Checkbox checked={selected.has(item.id)} onCheckedChange={()=>toggle(item.id)}/>Select</label></div><h3 className="mt-3 font-semibold">{item.citation}</h3><div className="mt-3 rounded-xl border border-sky-100 bg-sky-50/60 p-4"><p className="text-xs font-bold uppercase tracking-wider text-sky-800">Cambridge source text</p><p className="mt-1 leading-7">{item.evidence}</p></div>{item.classification&&<div className="mt-3 rounded-xl border border-violet-100 bg-violet-50/60 p-3"><p className="text-xs font-bold uppercase tracking-wider text-violet-700">Evidence classification</p><p className="mt-1 text-sm">{item.classification}</p></div>}<div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-600"><Badge variant="secondary">{item.lo?`9478 LO: ${item.lo}`:"No verified 9478 LO mapping"}</Badge><Badge variant="secondary">{item.relevance==="direct"?"Direct evidence":item.relevance==="close"?"Closely related evidence":"Contextual evidence"}</Badge><Badge variant="secondary">{item.links?.length?"Verified Drive source":item.sourceQuality}</Badge></div><div className="mt-4 flex flex-wrap items-center gap-4 border-t pt-3"><button onClick={()=>{setDetail(item);recordUsage("evidence_inspected",{source_type:item.kind,topic:item.topic||"Unmapped"})}} className="font-semibold text-teal-800">Inspect evidence</button>{item.links?.[0]&&<a href={viewUrl(item.links[0].id)} target="_blank" rel="noreferrer" onClick={()=>recordUsage("source_opened",{source_type:item.links[0].kind,topic:item.topic||"Unmapped"})} className="font-semibold text-teal-800">View original {item.links[0].kind==="Examiner Report"?"ER":item.links[0].kind} · p. {item.links[0].page||"—"} ↗</a>}{filters.q&&<Collapsible><CollapsibleTrigger className="flex items-center gap-1 text-sm font-semibold text-slate-500">Why this matched<ChevronDown className="h-4 w-4"/></CollapsibleTrigger><CollapsibleContent className="mt-2 max-w-xl text-sm text-slate-500">Matched the search and structured metadata with a relevance score of {item.matchScore}. This is generated metadata, not Cambridge wording.</CollapsibleContent></Collapsible>}</div></article>)}</div>
        {loading&&<p className="py-8 text-center text-slate-500">Loading source-backed records…</p>}{data.hasMore&&!loading&&<Button variant="outline" onClick={()=>setPage(p=>p+1)} className="mx-auto mt-5 flex">Load more records</Button>}
      </div>
    </div>
    {!!selected.size&&<div className="fixed bottom-5 left-1/2 z-40 flex w-[min(820px,calc(100%-2rem))] -translate-x-1/2 flex-wrap items-center justify-between gap-3 rounded-2xl bg-[#071a2d] px-5 py-3 text-white shadow-2xl"><div><strong>{selected.size} records selected</strong><p className="text-xs text-slate-300">Selected evidence remains source-linked.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={selectedItems.length<2} onClick={()=>setCompare(true)} className="border-slate-500 bg-transparent text-white"><Columns3 className="mr-2 h-4 w-4"/>Compare</Button><Button onClick={()=>onSend([...selected])} className="bg-teal-500 text-slate-950 hover:bg-teal-400"><Send className="mr-2 h-4 w-4"/>Send to Ask the Evidence</Button><Button variant="ghost" onClick={()=>setSelected(new Set())} className="text-white"><X className="h-4 w-4"/></Button></div></div>}
    <Sheet open={!!detail} onOpenChange={o=>!o&&setDetail(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-2xl"><SheetHeader><SheetTitle>Evidence detail</SheetTitle></SheetHeader>{detail&&<Detail item={detail}/>}</SheetContent></Sheet>
    <Sheet open={mobileFilters} onOpenChange={setMobileFilters}><SheetContent side="left" className="overflow-y-auto"><SheetHeader><SheetTitle>Corpus navigation</SheetTitle></SheetHeader><div className="p-4">{filterBody}</div></SheetContent></Sheet>
    <Dialog open={compare} onOpenChange={setCompare}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-6xl"><DialogHeader><DialogTitle>Compare evidence chronologically</DialogTitle></DialogHeader><p className="text-sm text-slate-500">The Hub does not automatically claim consistency or contradiction.</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{selectedItems.sort((a:RecordItem,b:RecordItem)=>Number(a.year)-Number(b.year)).map((x:RecordItem)=><article key={x.id} className="rounded-xl border p-4"><h3 className="font-semibold">{x.citation}</h3><div className="mt-2"><SourceBadge item={x}/></div><p className="mt-3 leading-7">{x.evidence}</p><p className="mt-3 text-sm text-slate-500">{x.lo||"No verified 9478 mapping"} · {x.alignment}</p></article>)}</div></DialogContent></Dialog>
  </section>
}
